POST  http://localhost:8080/links/return
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjMwMjE4NThlMDY0NzIzMzI0YTZkMmFhIiwiZW1haWwiOiJraGxhaWZAZ21haWwuY29tIiwiaWF0IjoxNjYxNjQwNzc1LCJleHAiOjE2NjE2NDQzNzV9.WhytPfIyKNSbv--rlL6pAtvGHmIujwXEdm7DlzJ0mlQ

{
     "linkId":"6307f3248035ce359c1c06b4",
     "userId":"63021858e064723324a6d2aa"
}